name: Receptacle

options:
  bundleIdPrefix: com.user
  deploymentTarget:
    macOS: "15.0"
    iOS: "18.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Debug

packages:
  # Local SPM package — provides ReceptacleCore types to all app targets.
  Receptacle:
    path: .
  # Google Sign-In SDK — used by OAuthManager for Gmail OAuth2.
  GoogleSignIn-iOS:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "9.0.0"
  # IMAP/SMTP — pure Swift, actor-based, Swift 6 native.
  SwiftMail:
    url: https://github.com/Cocoanetics/SwiftMail
    branch: main
  # RSS/Atom/JSON Feed parsing.
  FeedKit:
    url: https://github.com/nmdias/FeedKit
    from: "9.0.0"
  # OpenAI API client.
  OpenAI:
    url: https://github.com/MacPaw/OpenAI
    from: "0.2.0"
  # Anthropic/Claude API client.
  SwiftAnthropic:
    url: https://github.com/jamesrochabrun/SwiftAnthropic
    from: "1.0.0"
  # On-device speech transcription.
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    from: "0.9.0"
  # Markdown rendering in SwiftUI.
  textual:
    url: https://github.com/gonzalezreal/textual
    from: "0.3.0"
  # Markdown AST parser (wikilink detection).
  swift-markdown:
    url: https://github.com/apple/swift-markdown
    from: "0.4.0"
  # Outlook OAuth2.
  microsoft-authentication-library-for-objc:
    url: https://github.com/AzureAD/microsoft-authentication-library-for-objc
    from: "2.8.0"

configs:
  Debug:   debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_HARDENED_RUNTIME: YES

targets:

  # ── macOS App ──────────────────────────────────────────────────────────────
  ReceptacleApp:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    # xcodegen generates macOS/Info.plist from the `info:` block below,
    # sets INFOPLIST_FILE automatically, removes GENERATE_INFOPLIST_FILE.
    info:
      path: macOS/Info.plist
      properties:
        NSPrincipalClass: NSApplication
        # URL scheme required for Google Sign-In OAuth2 callback.
        # Set GOOGLE_REVERSED_CLIENT_ID in Xcode → Target → Build Settings
        # (User-Defined) to your reversed client ID, e.g.:
        #   com.googleusercontent.apps.123456789-abcdefghijklmnop
        # Obtain your client ID at console.cloud.google.com →
        # APIs & Services → Credentials → OAuth 2.0 Client IDs (Desktop app).
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: $(GOOGLE_REVERSED_CLIENT_ID)
            CFBundleURLSchemes:
              - $(GOOGLE_REVERSED_CLIENT_ID)
    sources:
      - path: macOS
        createIntermediateGroups: true
      - path: Shared
        createIntermediateGroups: true
    dependencies:
      - package: Receptacle
        product: Receptacle
      - package: GoogleSignIn-iOS
        product: GoogleSignIn
      - package: GoogleSignIn-iOS
        product: GoogleSignInSwift
      - package: SwiftMail
        product: SwiftMail
      - package: FeedKit
        product: FeedKit
      - package: OpenAI
        product: OpenAI
      - package: SwiftAnthropic
        product: SwiftAnthropic
      - package: WhisperKit
        product: WhisperKit
      - package: textual
        product: Textual
      - package: swift-markdown
        product: Markdown
      - package: microsoft-authentication-library-for-objc
        product: MSAL
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.user.receptacle
        PRODUCT_NAME: Receptacle
        # Distinguish Swift module name from SPM package "Receptacle"
        PRODUCT_MODULE_NAME: ReceptacleApp
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        # Reversed Google OAuth client ID for URL scheme registration.
        # Override this in Xcode Build Settings with your actual reversed client ID.
        GOOGLE_REVERSED_CLIENT_ID: com.receptacle.placeholder-google
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.user.receptacle.debug
          # Ad-hoc signing: run on your own Mac without a developer account.
          # Release builds use Automatic signing for notarisation.
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "-"
    scheme:
      testTargets:
        - ReceptacleTests
      gatherCoverageData: false

  # ── iOS App ────────────────────────────────────────────────────────────────
  Receptacle-iOS:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: iOS
        createIntermediateGroups: true
      - path: Shared
        createIntermediateGroups: true
    dependencies:
      - package: Receptacle
        product: Receptacle
      - package: GoogleSignIn-iOS
        product: GoogleSignIn
      - package: GoogleSignIn-iOS
        product: GoogleSignInSwift
      - package: SwiftMail
        product: SwiftMail
      - package: FeedKit
        product: FeedKit
      - package: OpenAI
        product: OpenAI
      - package: SwiftAnthropic
        product: SwiftAnthropic
      - package: WhisperKit
        product: WhisperKit
      - package: textual
        product: Textual
      - package: swift-markdown
        product: Markdown
      - package: microsoft-authentication-library-for-objc
        product: MSAL
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.user.receptacle.ios
        PRODUCT_NAME: Receptacle
        PRODUCT_MODULE_NAME: ReceptacleApp
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MACCATALYST: NO
        ENABLE_PREVIEWS: YES
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.user.receptacle.ios.debug
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "-"
    scheme:
      testTargets:
        - ReceptacleTests

  # ── Unit Tests ─────────────────────────────────────────────────────────────
  ReceptacleTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ReceptacleTests
        createIntermediateGroups: true
    dependencies:
      - package: Receptacle
        product: Receptacle
      - package: FeedKit
        product: FeedKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.user.receptacle.tests
        GENERATE_INFOPLIST_FILE: YES
    scheme:
      testPlans: []

  # ── UI Tests ───────────────────────────────────────────────────────────────
  ReceptacleUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: ReceptacleUITests
        createIntermediateGroups: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.user.receptacle.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: Receptacle
